version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=12345
      - PGDATABASE=web_forum
    networks:
      - app-network

  db:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - dz_data:/var/lib/postgresql/data
    environment:
      - PG_USER=postgres
      - PG_DB=web_forum
      - POSTGRES_PASSWORD=12345
    networks:
      - app-network

volumes:
  dz_data:

networks:
  app-network:
    driver: bridge
