version: '3'
services:
  app:
    restart: unless-stopped
    image: web-forum-image
    ports:
      - "3000:3000"
    environment:
      - PG_PORT=5432
      - PG_HOST=db
    networks:
      - dz-net

volumes:
  dz_data:

networks:
  dz-net: